import type { NextPage } from "next";
import Head from "next/head";
import Main from "../components/Langding/Main";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>프린팅사이다</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.png" />
      </Head>
      <Main />
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        ></a>
      </footer>
    </div>
  );
};

export default Home;
